[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps = 
    bblanchon/ArduinoJson@^7.0.4
    crankyoldgit/IRremoteESP8266@^2.8.6
    ; Для экрана раскомментируй, если подключишь
    ; adafruit/Adafruit SSD1306
    ; adafruit/Adafruit GFX Library
build_flags = 
    -D CORE_DEBUG_LEVEL=0
    -Wl,-z,muldefs
